/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED! */
#ifndef __TEST_MAP_IN_MAP_INVALID_SKEL_H__
#define __TEST_MAP_IN_MAP_INVALID_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct test_map_in_map_invalid {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *mim;
	} maps;
	struct {
		struct bpf_program *xdp_noop0;
	} progs;
	struct {
		struct bpf_link *xdp_noop0;
	} links;
};

static void
test_map_in_map_invalid__destroy(struct test_map_in_map_invalid *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
test_map_in_map_invalid__create_skeleton(struct test_map_in_map_invalid *obj);

static inline struct test_map_in_map_invalid *
test_map_in_map_invalid__open_opts(const struct bpf_object_open_opts *opts)
{
	struct test_map_in_map_invalid *obj;
	int err;

	obj = (struct test_map_in_map_invalid *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = test_map_in_map_invalid__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	test_map_in_map_invalid__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct test_map_in_map_invalid *
test_map_in_map_invalid__open(void)
{
	return test_map_in_map_invalid__open_opts(NULL);
}

static inline int
test_map_in_map_invalid__load(struct test_map_in_map_invalid *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct test_map_in_map_invalid *
test_map_in_map_invalid__open_and_load(void)
{
	struct test_map_in_map_invalid *obj;
	int err;

	obj = test_map_in_map_invalid__open();
	if (!obj)
		return NULL;
	err = test_map_in_map_invalid__load(obj);
	if (err) {
		test_map_in_map_invalid__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
test_map_in_map_invalid__attach(struct test_map_in_map_invalid *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
test_map_in_map_invalid__detach(struct test_map_in_map_invalid *obj)
{
	return bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *test_map_in_map_invalid__elf_bytes(size_t *sz);

static inline int
test_map_in_map_invalid__create_skeleton(struct test_map_in_map_invalid *obj)
{
	struct bpf_object_skeleton *s;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)
		goto err;
	obj->skeleton = s;

	s->sz = sizeof(*s);
	s->name = "test_map_in_map_invalid";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps)
		goto err;

	s->maps[0].name = "mim";
	s->maps[0].map = &obj->maps.mim;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs)
		goto err;

	s->progs[0].name = "xdp_noop0";
	s->progs[0].prog = &obj->progs.xdp_noop0;
	s->progs[0].link = &obj->links.xdp_noop0;

	s->data = (void *)test_map_in_map_invalid__elf_bytes(&s->data_sz);

	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return -ENOMEM;
}

static inline const void *test_map_in_map_invalid__elf_bytes(size_t *sz)
{
	*sz = 1984;
	return (const void *)"\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xc0\x05\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x08\0\
\x01\0\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x78\x64\
\x70\0\x6c\x69\x63\x65\x6e\x73\x65\0\x2e\x6d\x61\x70\x73\0\x74\x65\x73\x74\x5f\
\x6d\x61\x70\x5f\x69\x6e\x5f\x6d\x61\x70\x5f\x69\x6e\x76\x61\x6c\x69\x64\x2e\
\x63\0\x78\x64\x70\x5f\x6e\x6f\x6f\x70\x30\0\x5f\x6c\x69\x63\x65\x6e\x73\x65\0\
\x6d\x69\x6d\0\x2e\x42\x54\x46\0\x2e\x42\x54\x46\x2e\x65\x78\x74\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x23\0\0\0\x04\0\xf1\xff\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x3d\0\0\0\x12\0\x03\0\0\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x47\0\0\0\x11\0\x04\0\
\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\x50\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\0\x18\0\
\0\0\0\0\0\0\xb4\0\0\0\x02\0\0\0\x95\0\0\0\0\0\0\0\x47\x50\x4c\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x78\
\x02\0\0\x78\x02\0\0\x72\x01\0\0\0\0\0\0\0\0\0\x02\x03\0\0\0\x01\0\0\0\0\0\0\
\x01\x04\0\0\0\x20\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x0c\0\
\0\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x06\0\0\0\0\0\0\
\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x02\x08\0\0\0\
\x19\0\0\0\0\0\0\x08\x09\0\0\0\x1f\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\
\0\0\0\x02\x0b\0\0\0\x2c\0\0\0\x04\0\0\x04\x20\0\0\0\x32\0\0\0\x0c\0\0\0\0\0\0\
\0\x37\0\0\0\x07\0\0\0\x40\0\0\0\x3b\0\0\0\x0e\0\0\0\x80\0\0\0\x41\0\0\0\x0f\0\
\0\0\xc0\0\0\0\0\0\0\0\0\0\0\x02\x0d\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\
\x04\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\x02\x02\0\0\0\0\0\0\0\0\0\0\x02\x10\0\0\0\0\
\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\
\0\x0a\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\x04\x18\0\0\0\x32\0\0\0\x01\0\0\
\0\0\0\0\0\x41\0\0\0\x05\0\0\0\x40\0\0\0\x37\0\0\0\x07\0\0\0\x80\0\0\0\x4d\0\0\
\0\x11\0\0\0\xc0\0\0\0\x54\0\0\0\0\0\0\x0e\x12\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\
\x02\x15\0\0\0\x58\0\0\0\x06\0\0\x04\x18\0\0\0\x5f\0\0\0\x08\0\0\0\0\0\0\0\x64\
\0\0\0\x08\0\0\0\x20\0\0\0\x6d\0\0\0\x08\0\0\0\x40\0\0\0\x77\0\0\0\x08\0\0\0\
\x60\0\0\0\x87\0\0\0\x08\0\0\0\x80\0\0\0\x96\0\0\0\x08\0\0\0\xa0\0\0\0\0\0\0\0\
\x01\0\0\x0d\x02\0\0\0\xa5\0\0\0\x14\0\0\0\xa9\0\0\0\x01\0\0\x0c\x16\0\0\0\xb3\
\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x18\0\0\0\x04\
\0\0\0\x04\0\0\0\xb8\0\0\0\0\0\0\x0e\x19\0\0\0\x01\0\0\0\x60\x01\0\0\x01\0\0\
\x0f\x04\0\0\0\x1a\0\0\0\0\0\0\0\x04\0\0\0\x68\x01\0\0\x01\0\0\x0f\x18\0\0\0\
\x13\0\0\0\0\0\0\0\x18\0\0\0\0\x69\x6e\x74\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\
\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x5f\x5f\x75\x33\x32\0\x75\x6e\
\x73\x69\x67\x6e\x65\x64\x20\x69\x6e\x74\0\x69\x6e\x6e\x65\x72\0\x74\x79\x70\
\x65\0\x6b\x65\x79\0\x76\x61\x6c\x75\x65\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\
\x65\x73\0\x76\x61\x6c\x75\x65\x73\0\x6d\x69\x6d\0\x78\x64\x70\x5f\x6d\x64\0\
\x64\x61\x74\x61\0\x64\x61\x74\x61\x5f\x65\x6e\x64\0\x64\x61\x74\x61\x5f\x6d\
\x65\x74\x61\0\x69\x6e\x67\x72\x65\x73\x73\x5f\x69\x66\x69\x6e\x64\x65\x78\0\
\x72\x78\x5f\x71\x75\x65\x75\x65\x5f\x69\x6e\x64\x65\x78\0\x65\x67\x72\x65\x73\
\x73\x5f\x69\x66\x69\x6e\x64\x65\x78\0\x63\x74\x78\0\x78\x64\x70\x5f\x6e\x6f\
\x6f\x70\x30\0\x63\x68\x61\x72\0\x5f\x6c\x69\x63\x65\x6e\x73\x65\0\x2f\x72\x6f\
\x6f\x74\x2f\x72\x70\x6d\x62\x75\x69\x6c\x64\x2f\x42\x55\x49\x4c\x44\x2f\x6b\
\x65\x72\x6e\x65\x6c\x2d\x35\x2e\x31\x34\x2e\x30\x2d\x31\x36\x32\x2e\x36\x2e\
\x31\x2e\x65\x6c\x39\x5f\x31\x2f\x6c\x69\x6e\x75\x78\x2d\x35\x2e\x31\x34\x2e\
\x30\x2d\x31\x36\x32\x2e\x36\x2e\x31\x2e\x65\x6c\x39\x2e\x78\x38\x36\x5f\x36\
\x34\x2f\x74\x6f\x6f\x6c\x73\x2f\x74\x65\x73\x74\x69\x6e\x67\x2f\x73\x65\x6c\
\x66\x74\x65\x73\x74\x73\x2f\x62\x70\x66\x2f\x70\x72\x6f\x67\x73\x2f\x74\x65\
\x73\x74\x5f\x6d\x61\x70\x5f\x69\x6e\x5f\x6d\x61\x70\x5f\x69\x6e\x76\x61\x6c\
\x69\x64\x2e\x63\0\x09\x72\x65\x74\x75\x72\x6e\x20\x58\x44\x50\x5f\x50\x41\x53\
\x53\x3b\0\x6c\x69\x63\x65\x6e\x73\x65\0\x2e\x6d\x61\x70\x73\0\x78\x64\x70\0\0\
\0\0\0\0\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\x1c\0\0\0\x30\0\
\0\0\0\0\0\0\x08\0\0\0\x6e\x01\0\0\x01\0\0\0\0\0\0\0\x17\0\0\0\x10\0\0\0\x6e\
\x01\0\0\x01\0\0\0\0\0\0\0\xc1\0\0\0\x4e\x01\0\0\x02\x5c\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x03\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x40\0\0\0\0\0\0\0\x62\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x09\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa8\0\0\0\
\0\0\0\0\x90\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\
\0\x11\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x38\x01\0\0\0\0\0\0\
\x10\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x15\0\0\0\
\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x48\x01\0\0\0\0\0\0\x04\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1d\0\0\0\x01\0\0\0\x03\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x50\x01\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x54\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x68\x01\0\0\0\0\0\0\x02\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x59\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x70\x05\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0";
}

#endif /* __TEST_MAP_IN_MAP_INVALID_SKEL_H__ */
