'\" t
.\"     Title: perf
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/30/2022
.\"    Manual: perf Manual
.\"    Source: perf
.\"  Language: English
.\"
.TH "PERF" "1" "09/30/2022" "perf" "perf Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
perf \- Performance analysis tools for Linux
.SH "SYNOPSIS"
.sp
.nf
\fIperf\fR [\-\-version] [\-\-help] [OPTIONS] COMMAND [ARGS]
.fi
.SH "OPTIONS"
.PP
\-h, \-\-help
.RS 4
Run perf help command\&.
.RE
.PP
\-v, \-\-version
.RS 4
Display perf version\&.
.RE
.PP
\-vv
.RS 4
Print the compiled\-in status of libraries\&.
.RE
.PP
\-\-exec\-path
.RS 4
Display or set exec path\&.
.RE
.PP
\-\-html\-path
.RS 4
Display html documentation path\&.
.RE
.PP
\-p, \-\-paginate
.RS 4
Set up pager\&.
.RE
.PP
\-\-no\-pager
.RS 4
Do not set pager\&.
.RE
.PP
\-\-buildid\-dir
.RS 4
Setup buildid cache directory\&. It has higher priority than buildid\&.dir config file option\&.
.RE
.PP
\-\-list\-cmds
.RS 4
List the most commonly used perf commands\&.
.RE
.PP
\-\-list\-opts
.RS 4
List available perf options\&.
.RE
.PP
\-\-debugfs\-dir
.RS 4
Set debugfs directory or set environment variable PERF_DEBUGFS_DIR\&.
.RE
.PP
\-\-debug
.RS 4
Setup debug variable (see list below) in value range (0, 10)\&. Use like: \-\-debug verbose # sets verbose = 1 \-\-debug verbose=2 # sets verbose = 2
.sp
.if n \{\
.RS 4
.\}
.nf
List of debug variables allowed to set:
  verbose          \- general debug messages
  ordered\-events   \- ordered events object debug messages
  data\-convert     \- data convert command debug messages
  stderr           \- write debug output (option \-v) to stderr
                     in browser mode
  perf\-event\-open  \- Print perf_event_open() arguments and
                     return value
.fi
.if n \{\
.RE
.\}
.RE
.SH "DESCRIPTION"
.sp
Performance counters for Linux are a new kernel\-based subsystem that provide a framework for all things performance analysis\&. It covers hardware level (CPU/PMU, Performance Monitoring Unit) features and software features (software counters, tracepoints) as well\&.
.SH "SEE ALSO"
.sp
\fBperf-stat\fR(1), \fBperf-top\fR(1), \fBperf-record\fR(1), \fBperf-report\fR(1), \fBperf-list\fR(1)
.sp
\fBperf-annotate\fR(1),\fBperf-archive\fR(1), \fBperf-bench\fR(1), \fBperf-buildid-cache\fR(1), \fBperf-buildid-list\fR(1), \fBperf-c2c\fR(1), \fBperf-config\fR(1), \fBperf-data\fR(1), \fBperf-diff\fR(1), \fBperf-evlist\fR(1), \fBperf-ftrace\fR(1), \fBperf-help\fR(1), \fBperf-inject\fR(1), \fBperf-intel-pt\fR(1), \fBperf-iostat\fR(1), \fBperf-kallsyms\fR(1), \fBperf-kmem\fR(1), \fBperf-kvm\fR(1), \fBperf-lock\fR(1), \fBperf-mem\fR(1), \fBperf-probe\fR(1), \fBperf-sched\fR(1), \fBperf-script\fR(1), \fBperf-test\fR(1), \fBperf-trace\fR(1), \fBperf-version\fR(1)
