'\" t
.\"     Title: perf-iostat
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/30/2022
.\"    Manual: perf Manual
.\"    Source: perf
.\"  Language: English
.\"
.TH "PERF\-IOSTAT" "1" "09/30/2022" "perf" "perf Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
perf-iostat \- Show I/O performance metrics
.SH "SYNOPSIS"
.sp
.nf
\fIperf iostat\fR list
\fIperf iostat\fR <ports> \-\- <command> [<options>]
.fi
.SH "DESCRIPTION"
.sp
Mode is intended to provide four I/O performance metrics per each PCIe root port:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Inbound Read \- I/O devices below root port read from the host memory, in MB
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Inbound Write \- I/O devices below root port write to the host memory, in MB
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Outbound Read \- CPU reads from I/O devices below root port, in MB
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Outbound Write \- CPU writes to I/O devices below root port, in MB
.RE
.SH "OPTIONS"
.PP
<command>\&...
.RS 4
Any command you can specify in a shell\&.
.RE
.PP
list
.RS 4
List all PCIe root ports\&.
.RE
.PP
<ports>
.RS 4
Select the root ports for monitoring\&. Comma\-separated list is supported\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
List all PCIe root ports (example for 2\-S platform):
.sp
.if n \{\
.RS 4
.\}
.nf
$ perf iostat list
S0\-uncore_iio_0<0000:00>
S1\-uncore_iio_0<0000:80>
S0\-uncore_iio_1<0000:17>
S1\-uncore_iio_1<0000:85>
S0\-uncore_iio_2<0000:3a>
S1\-uncore_iio_2<0000:ae>
S0\-uncore_iio_3<0000:5d>
S1\-uncore_iio_3<0000:d7>
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Collect metrics for all PCIe root ports:
.sp
.if n \{\
.RS 4
.\}
.nf
$ perf iostat \-\- dd if=/dev/zero of=/dev/nvme0n1 bs=1M oflag=direct
357708+0 records in
357707+0 records out
375083606016 bytes (375 GB, 349 GiB) copied, 215\&.974 s, 1\&.7 GB/s
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Performance counter stats for \*(Aqsystem wide\*(Aq:
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
   port             Inbound Read(MB)    Inbound Write(MB)    Outbound Read(MB)   Outbound Write(MB)
0000:00                    1                    0                    2                    3
0000:80                    0                    0                    0                    0
0000:17               352552                   43                    0                   21
0000:85                    0                    0                    0                    0
0000:3a                    3                    0                    0                    0
0000:ae                    0                    0                    0                    0
0000:5d                    0                    0                    0                    0
0000:d7                    0                    0                    0                    0
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Collect metrics for comma\-separated list of PCIe root ports:
.sp
.if n \{\
.RS 4
.\}
.nf
$ perf iostat 0000:17,0:3a \-\- dd if=/dev/zero of=/dev/nvme0n1 bs=1M oflag=direct
357708+0 records in
357707+0 records out
375083606016 bytes (375 GB, 349 GiB) copied, 197\&.08 s, 1\&.9 GB/s
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Performance counter stats for \*(Aqsystem wide\*(Aq:
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
   port             Inbound Read(MB)    Inbound Write(MB)    Outbound Read(MB)   Outbound Write(MB)
0000:17               358559                   44                    0                   22
0000:3a                    3                    2                    0                    0
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
197\&.081983474 seconds time elapsed
.fi
.if n \{\
.RE
.\}
.RE
.SH "SEE ALSO"
.sp
\fBperf-stat\fR(1)
